# Generated by Django 5.1.2 on 2024-10-26 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('story', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField()),
                ('journal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='story.journal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.TextField()),
                ('image_gen_prompt', models.TextField()),
                ('storyline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.storyline')),
            ],
        ),
    ]
