# Generated by Django 5.1.2 on 2024-10-26 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGenBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_count', models.PositiveSmallIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storyline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.storyline')),
            ],
        ),
        migrations.CreateModel(
            name='FrameImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.frame')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.imagegenbatch')),
            ],
        ),
    ]
