# Generated by Django 5.1.2 on 2024-10-26 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_imagegenbatch_frameimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frameimages',
            name='frame',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='models.frame'),
        ),
    ]
