# Generated by Django 5.1.2 on 2024-10-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='june', max_length=50),
            preserve_default=False,
        ),
    ]
